name: Test

on: workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - name: install lftp
        working-directory: ${{github.workspace}}
        shell: bash
        run:  sudo apt-get install lftp

      - name: temp file
        working-directory: ${{github.workspace}}
        shell: bash
        run: mkdir output &&
             cd output &&
             echo blabla > fake_companion.dmg
        
    - name: ftp
      working-directory: ${{github.workspace}}
      shell: bash
      env: 
            USER: ${{ secrets.FTP_USERNAME }}
            PASSWORD: ${{ secrets.FTP_PASSWORD }}
            SERVER: ${{ secrets.FTP_SERVER }}
      run:  lftp -c "open -u USER,PASSWORD SERVER; mput ${{github.workspace}}/output/*.dmg"
